version: '3.1'

services:
  postgres:
    image: postgres
    container_name: rent_a_car_camp_container
    restart: always
    environment:
      POSTGRES_DB: rent_a_car_camp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
